services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pc_builder_db
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  app-service:
    image: joeldomene/app-service:latest
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pc_builder_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      UTILITY_SERVICE_URL: http://utility-service:8080/api/utility
    depends_on:
      db:
        condition: service_healthy

  utility-service:
    image: joeldomene/utility-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pc_builder_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
