# 1. NOMBRE DE LA APLICACIÓN
spring.application.name=backend

# 2. CONFIGURACIÓN DEL PUERTO Y HTTPS (Requisito Práctica 2)
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

# 3. CONFIGURACIÓN DE LA BASE DE DATOS (MySQL)
# Sustituye 'nombre_tu_bd' por el nombre que hayas puesto en MySQL Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/pc_builder_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. CONFIGURACIÓN DE JPA / HIBERNATE
# 'update' crea las tablas automáticamente basándose en tus clases Java @Entity
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 5. CONFIGURACIÓN DE MUSTACHE (Para que reconozca tus HTML)
spring.mustache.prefix=classpath:/templates/
spring.mustache.suffix=.html
spring.mustache.cache=false

spring.profiles.active=dev

# Configuración para Mailtrap (ejemplo)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=2bf52467043681
spring.mail.password=faa0be98daaff6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Endpoint for utility-service REST API
utility.service.url=http://localhost:8080/api/utility

# Configuración de SpringDoc OpenAPI para la documentación de la API REST
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/api-docs.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true