spring.application.name=utility-service
server.port=8080

# Configure email SMTP settings locally if you want to send emails.
# Do not commit real SMTP credentials to the repository.
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=2bf52467043681
spring.mail.password=faa0be98daaff6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
